# Swagger definition for the TranscodeE16 Manifest
swagger: '2.0'

# Metadata
info:
  version: "0.0.1"
  title: AdCentsE16
  description: ''
  termsOfService: https://opensource.org/licenses/MIT
  contact:
    email: james@esixteen.co
    name: eSixteen.co
    url: https://www.esixteen.co/
  x-21-usage: 'Use the available API endpoints to index and search for your documents.'
  x-21-quick-buy: "21 buy url http://10.244.119.122:11016/status"
  x-21-category: utilities
  x-21-github-profile-url: https://github.com/pooleja
  x-21-github-project-url: https://github.com/pooleja/AdCentsE16
  x-21-keywords: [search, service, index, elastic, elasticsearch, iot, sensor]
  x-21-total-price:
     min: 10
     max: 10000
host: 10.244.119.122:11016
schemes:
   - http
basePath: /
x-21-manifest-path: /manifest

# Available paths for the app
paths:
  /manifest:
    get:
      description: Gets the `manifest` of the application.

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successfully found the manifest YAML file and returned it to client.
