# Swagger definition for the TranscodeE16 Manifest
swagger: '2.0'

# Metadata
info:
  version: "0.0.1"
  title: AdCentsE16
  description: ''
  termsOfService: https://opensource.org/licenses/MIT
  contact:
    email: james@esixteen.co
    name: eSixteen.co
    url: https://www.esixteen.co/
  x-21-usage: 'Use the available API endpoints to index and search for your documents.'
  x-21-quick-buy: "21 buy http://[fcce:a977:eef6:442a:aaf8:0000:0000:0001]:11116/registrations"
  x-21-category: utilities
  x-21-github-profile-url: https://github.com/pooleja
  x-21-github-project-url: https://github.com/pooleja/AdCentsE16
  x-21-keywords: [ads, revenue, money, price, advertisement, ad]
  x-21-total-price:
     min: 10
     max: 10000
host: [fcce:a977:eef6:442a:aaf8:0000:0000:0001]:11116
schemes:
   - http
basePath: /

# Available paths for the app
paths:
  /registrations:
    get:
      description: Gets a list of web pages that have ads available for bidding.

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successfully returns the site URLs.
